### ISSUE TITLE
docker-compose-lan

### ISSUE THREAD

**Issue by Torhamilton** [c0sogi/LLMChat#30]
Trying to install into a LAN network so everyone within the network can use. I added IP as `HOST_MAIN="192.168.2.202"`. The chat interface is reachable but authentication is denied

**Comment by c0sogi** [comment]
The issue appears to be caused by the js_initializer not properly initializing the authentication URL within the JS. Did you set your environment to local, then you're only connecting to localhost.

To fix this, you can disable the `js_url_initializer` function, find the URLs you were accessing before in main.dart.js, and replace them all with `192.168.2.202:port`.

2. the best way is to build the Flutter app by setting host, websocketSchema, httpSchema correctly in `app_config.dart` and then run build-web.bat. to do this, you need to have the flutter sdk installed.
